#ifndef SRC_ESP32_THINGPROPERTIES_H_
#define SRC_ESP32_THINGPROPERTIES_H_

// Code adapted from Arduino IoT Cloud - https://cloud.arduino.
#include <ArduinoIoTCloud.h>
#include <esp32/secrets.h>
#include <esp32/cloud_callback/cloud_callback.h>
// #include <Arduino_ConnectionHandler.h>

void initProperties()
{
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

  // Initialize default values for Arduino Cloud variables
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::SYNC, resetCloudVariables);

  // Generated by Arduino Cloud Dashboard
  ArduinoCloud.addProperty(line_follower_mode, READWRITE, ON_CHANGE, onLineFollowerModeChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection("none", "none");

#endif // SRC_ESP32_THINGPROPERTIES_H_
