#ifndef INCLUDE_SERIAL_TRANSFER_SERIAL_TRANSFER_H_
#define INCLUDE_SERIAL_TRANSFER_SERIAL_TRANSFER_H_
#include <SerialTransfer.h>

extern SerialTransfer serialTransfer;

#endif  // INCLUDE_SERIAL_TRANSFER_SERIAL_TRANSFER_H_
