#ifndef PINS_LINE_FOLLOWER_H
#define PINS_LINE_FOLLOWER_H

// H-Bridge (L9110S) Dual Channel
#define MOTOR_RIGHT_FORWARD_PIN 3 // PWM PIN
#define MOTOR_RIGHT_BACKWARD_PIN 2

#define MOTOR_LEFT_FORWARD_PIN 5 // PWM PIN
#define MOTOR_LEFT_BACKWARD_PIN 4

#endif
